project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "files/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl
description-meta: "Estadística Correlacional - Asociación bivariada e inferencia"

website:
  title: "Estadística Correlacional"
  site-url: "https://correlacional.netlify.app"

  favicon: "/files/logo-correlacional.png"

  twitter-card:
    image: "/files/social-image-sp23.png"
    card-style: summary_large_image
    creator: "@andrewheiss"
    # site: "@andrewheiss"

  open-graph:
    image: "/files/social-image-sp23.png"
    locale: es

  navbar:
    pinned: true
    background: "#BC3C6F"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Clases"
        file: content/index.qmd
      - text: "Prácticos"
        file: assignment/index.qmd
      - text: "Recursos"
        file: resource/index.qmd
      - text: "Noticias"
        file: news/index.qmd
      - icon: cloud-fill
        href: "https://rstudio.cloud"
        aria-label: RStudio.cloud

  sidebar:
    - title: "Clases"
      style: "docked"
      search: false
      lang: es
      background: dark
      contents:
        - section: "Sobre clases"
          contents:
            - content/index.qmd
        - section: "Sesiones"
          contents:
            - text: "Sesión 1"
              file: content/01-content.qmd
            - text: "Sesión 2"
              file: content/02-content.qmd

    - title: "Prácticos"
      contents:
        - section: "Sobre prácticos"
          contents:
            - assignment/index.qmd
        - section: "Guías prácticos"
          contents:
            - assignment/01-problem-set.qmd
            - assignment/02-problem-set.qmd


    - title: "Examples"
      contents:
        - section: "Overview"
          contents:
            - example/index.qmd
        - section: "Simulated data"
          contents:
            - text: "Random numbers"
              file: example/random-numbers.qmd
            - text: "Synthetic data"
              file: example/synthetic-data.qmd
        - section: "Examples"
          contents:
            - example/rstudio-tidyverse.qmd
            - example/regression.qmd
            - example/dags.qmd
            - example/po-ate-cate.qmd
            - text: "RCTs"
              file: example/rcts.qmd
            - text: "Matching and IPW"
              file: example/matching-ipw.qmd
            - text: "Robust standard errors"
              file: example/standard-errors.qmd
            - text: "Unobserved confounding"
              file: example/confounding-sensitivity.qmd
            - text: "Diff-in-diff"
              file: example/diff-in-diff.qmd
            - example/rdd.qmd
            - example/iv.qmd
            - text: "ITT and CACE"
              file: example/cace.qmd
            - example/rdd-fuzzy.qmd

    - title: "Resources"
      contents:
        - section: "Overview"
          contents:
            - resource/index.qmd
            - resource/r.qmd
            - resource/style.qmd
            - resource/data.qmd
            - resource/citations.qmd
            - resource/bayes.qmd
            - resource/zilch.qmd
        - section: "Study guides"
          contents:
            - resource/exam1.qmd
            - resource/exam2.qmd
        - section: "Guides"
          contents:
            - resource/install.qmd
            - resource/markdown.qmd
            - resource/rmarkdown.qmd
            - resource/unzipping.qmd

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
