project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "files/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/images/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl
description-meta: "Estadística Correlacional - Asociación, inferencia y reporte"

website:
  title: "Estadística Correlacional"
  site-url: "https://correlacional.netlify.app"

  favicon: "/files/logo-correlacional-transp.png"

  # twitter-card:
  #  image: "/files/social-image-sp23.png"
  #  card-style: summary_large_image
  #  creator: "@andrewheiss"
    # site: "@andrewheiss"

  open-graph:
    image: "/files/logo-correlacional.png" # cambiar luego
    locale: es

  navbar:
    pinned: true
    background: "#BC3C6F"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Clases"
        file: content/index.qmd
      - text: "Prácticos"
        file: assignment/index.qmd
      - text: "Recursos"
        file: resource/index.qmd
      - text: "Noticias"
        file: news/index.qmd
      - icon: cloud-fill
        href: "https://rstudio.cloud"
        aria-label: RStudio.cloud

  sidebar:
    - title: "Clases"
      style: "docked"
      search: false
      lang: es
      background: dark
      contents:
        - section: "Sobre clases"
          contents:
            - content/index.qmd
        - section: "Sesiones"
          contents:
            - text: "Sesión 1"
              file: content/01-content.qmd
            - text: "Sesión 2"
              file: content/02-content.qmd

    - title: "Prácticos"
      contents:
        - section: "Sobre prácticos"
          contents:
            - assignment/index.qmd
        - section: "Guías"
          contents:
            - text: "1: Reportes dinámicos 1"
              file: assignment/01-practico.qmd

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
