---
title: Programa
lang: es
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tibble)
library(pander)
```

::: {.grid .course-details .course-details-smaller}

::: {.g-col-6}
### Profesor

- {{< fa user >}} &nbsp; [{{< var instructor.name >}}]({{< var instructor.url >}})
- {{< fa university >}} &nbsp; {{< var instructor.office >}}
- {{< fa envelope >}} &nbsp; <a href="mailto:{{< var instructor.email >}}">{{< var instructor.email >}}</a>
- {{< fa calendar-check >}} &nbsp; [Agendar reunión]({{< var instructor.appointment_url >}})
:::

::: {.g-col-6}
### Detales del curso

- {{< fa calendar >}} &nbsp; {{< var course.days >}}
- {{< fa calendar-alt >}} &nbsp; {{< var course.dates >}}
- {{< fa clock >}} &nbsp; {{< var course.time >}}
- {{< fa location-dot >}} &nbsp; {{< var course.location >}}
- {{< fa brands slack >}} &nbsp; [Slack]({{< var course.slack >}})
:::

:::

## Sobre el sentido general del curso

En este curso vamos a aprender tres cosas principales:

- **inferencia**: los resultados que encontramos en nuestra muestra, ¿se encuentran también en la población de la cual proviene la muestra?

- medidas de **asociación** entre variables: tamaño y significación estadística 

- **reporte y reproducibilidad** de los análisis estadísticos: nuestros análisis se reflejan en productos como tablas y gráficos. No basta con entenderlos e interpretarlos, sino también es fundamental una buena comunicación.

## Propósito general del curso

Al finalizar el curso los estudiantes conocerán los fundamentos del análisis estadístico inferencial. Se espera que los estudiantes sean capaces de:

- elaborar de manera pertinente hipótesis estadísticas
- aplicar estadísticos de asociación y correlación, a partir de los cuáles puedan desarrollar análisis de problemas sociales
- corroborar el cumplimiento de las condiciones de aplicación de cada estadístico
- utilizar diferentes softwares de análisis estadístico
- contrastar hipótesis de investigación
- elaborar conclusiones integrando fundamentos teóricos con herramientas de análisis estadístico de resultados. 

Complementariamente se espera que los estudiantes adquieran herramientas que les permitan comunicar resultados de investigación en contextos sociales, profesionales y académicos.

## Competencias

1a. Delimitar, conceptualizar y analizar diversos objetos de investigación social, con especial énfasis en aquellos relacionados con los procesos de transformación del país y Latinoamérica

1b. Manejar diversas estrategias metodológicas de las ciencias sociales

1c.  Manejar un conjunto de herramientas para el procesamiento y análisis de información
 
1d.  Transmitir los conocimientos derivados de la práctica investigativa, así como aquellos adquiridos durante el proceso formativo.

## Subcompetencias

- 1.4  Contribuir a generar conocimiento sociológico en el marco de estudios y/o procesos de investigación donde se articulen creativamente las dimensiones teórica, metodológica y práctica.

- 1.5 Comunicar los saberes disciplinares de manera pertinente a las características de distintos contextos y audiencias, utilizando diversas estrategias y formatos. 

## Resultados del aprendizaje

1. Comprende, domina y es capaz de explicar los elementos conceptuales subyacentes a la determinación de la asociación poblacional entre dos variables a partir del análisis de una muestra, y es capaz de traducir hipótesis derivadas de la teoría sociológica en hipótesis estadísticas posibles de contrastar empíricamente con los datos.
   
2. Es capaz de seleccionar y usar herramientas estadísticas adecuadas para evaluar la asociación entre dos variables considerando las características de los datos y las condiciones de aplicación de cada técnica.
   
3. Logra interpretar desde un punto de vista estadístico y sociológico los resultados derivados de pruebas estadísticas para analizar la relación entre dos variables.
   
4. Es capaz de reportar y comunicar adecuada y eficientemente los resultados de los análisis estadísticos

##  Saberes / Contenidos

### Unidad I: Asociación entre dos variables cuantitativas.

- Descripción, asociación, y explicación en estadística. La importancia del análisis de covariación entre variables. La inferencia estadística: tipos y rol en el análisis descriptivo, asociativo y explicativo.
- Concepto de covarianza y relación/correlación lineal versus relación no-lineal entre variables.
- Correlación de Pearson: supuestos y condiciones de aplicación, interpretación de resultados como tamaño efecto según criterios de Cohen. El coeficiente de determinación, utilidad e interpretación.

### Unidad II: Inferencia y asociación
- Asociación entre una variable cuantitativa y una dicotómica como intervalos de confianza de medias y proporciones usando distribución Z y revisión de conceptos fundamentales de inferencia: área de una distribución, probabilidades en la curva normal, error Tipo I, y error tipo II.
- Asociación entre una variable cuantitativa y una dicotómica como diferencia de medias y proporciones con prueba Z; revisión y análisis de valor de Z observado, el concepto de valor-p y determinación del tamaño del efecto con d de Cohen. 
- Generalización de intervalos de confianza y pruebas de diferencia de medias y proporciones en dos grupos en muestras pequeñas usando distribución t de Student; revisión de concepto de grados de libertad.
- Generalizaciones de esta lógica: Prueba t de Student e intervalos de confianza en correlaciones de Pearson; Comparación de medias de tres o más grupos con ANOVA e intervalos de confianza corregidos por número de comparaciones.

### Unidad III: Asociación con variables categóricas 

- El uso de tablas de contingencia y la determinación de la asociación: uso de frecuencias observadas, porcentajes fila, columna y totales.
- Evaluación de la asociación poblacional mediante Chi Cuadrado: el concepto de frecuencias esperadas y observadas. Estimación e interpretación de resultados y medición de tamaño efecto.
- Breve mirada a estadísticos de correlación para variables categóricas: la correlación tetracórica y policórica.

## Metodología
1. Sesiones de clases lectivas presenciales semanales, donde se presentarán los aspectos centrales de los contenidos correspondientes a la semana.

2. Prácticos online semanales: cada tema de las sesiones se acompaña de una guía práctica de aplicación de contenidos. Estas guías están diseñadas para ser desarrolladas de manera autónoma por cada estudiante semana a semana. También serán desarrolladas y revisadas cada semana en grupos pequeños con supervisión de ayudantes para dar mayor oportunidad de participación y resolver las dudas respectivas. Existe un reporte de progreso asociado a estas guías que deberá ser completado semanalmente con fines de monitoreo y retroalimentación.

3. Trabajos: se desarrollarán trabajos de investigación que permitirán a l_s participantes aplicar contenidos y recibir retroalimentación de su desempeño. Los trabajos serán asesorados por ayudantes que se asignarán a cada grupo.

## Evaluación

El curso tendrá tres instancias de evaluación:

- Evaluación 1: prueba correlación lineal (30%).
- Evaluación 2: prueba inferencia estadística (30%)
- Evaluación 3: trabajo grupal (40%)

La nota ponderada de las evaluaciones equivaldrá al 60% de la nota del curso y el examen final al 40% restante.

## Inasistencias y atraso en entregas

Los justificativos por ausencia o atraso se realizan en la secretaría de carrera. Lo que la carrera informe como justificado, es lo que se va a considerar en el curso. **No enviar justificativos a equipo docente y a ayudantes directamente**, no es necesario ni apropiado para l_s estudiantes tener que exponer situaciones personales.

En caso de faltar a alguna de las evaluaciones existirá una única fecha para evaluaciones recuperativas. Si en esa fecha no es posible asistir por motivos justificados, entonces pasará directo a examen. 

En el caso de los trabajos, en caso de atraso se descontará 0.5 por día adicional. Si el trabajo no se entrega luego del tercer día de atraso será calificado con nota 1.0

## Requisitos de aprobación 

Requisitos de eximición a examen:

- contar con un promedio ponderado igual o superior a 5.5
- no tener nota bajo 4.0 en ninguna de las evaluaciones

Requisitos para presentación a examen:

- Podrán presentarse al examen de primera oportunidad los estudiantes que hayan obtenido una calificación final igual o superior a 3.5.

- El examen de segunda oportunidad será para aquellos estudiantes que presenten una nota igual o inferior a 3.5 o aquellos que en el examen de primera oportunidad no hubiesen logrado una nota igual o superior a 4.0.

## Bibliografía Obligatoria 

Capítulos correspondientes a cada sesión de los siguientes textos principales:

- Ritchey, F. (2008) Estadística para las ciencias sociales. McGraw-Hill: México.
- Moore (2010) Estadística aplicada básica. Barcelona: Antoni Bosch. 
- Pardo, Ruiz y San Martín (2015). Análisis de Datos en Ciencias Sociales y de la Salud I. Editorial Síntesis: Madrid.

## Bibliografía Complementaria

Wickham, H., & Grolemund, G. (2016). R for data science: import, tidy, transform, visualize, and model data (First edition). Sebastopol: O’Reilly.

Field, A., Milles, J., & Field, Z. (2012). Discovering statistics using R. London: Sage.

Salkind, N. J. (Ed.). (2010). Encyclopedia of research design (Vol. 1). Sage.

Levin, J. & Levin, W. (1997). Fundamentos de Estadística en la Investigación Social (Vol.2). Oxford University Press. 


## VARIOS

- Se espera asistencia y participación activa, tanto a las sesiones lectivas como a las prácticas. Se pasará lista en todas las sesiones. No habrá penalización por inasistencia, pero si llevaremos registro principalmente con objetivos de monitoreo y retroalimentación del curso 

- Las clases en general se acompañan de documentos de presentación, que estarán disponibles antes de la sesión en la página de Contenidos, y están desarrollados con base en Rmarkdown/XaringanRmarkdown/ Xaringan. Estos documentos no son:

  - “la clase”
  - autoexplicativos (ni aspiran a serlo)
  - “el ppt” (ni  “la ppt”)


- Políticas de participación y trato: se espera y enfatiza la participación por distintos canales disponibles. También se enfatiza un trato respetuoso y horizontal. Quienes están tomando este curso serán referidos como participantes y/o estudiantes, evitar el uso de “l_s cabr_s” o “l_s chiquill_s”, que si bien puede intentar transmitir cercanía finalmente expresan minimización de la contraparte. Quien no se sienta tratad_ apropiadamente o vea que otr_s no lo están siendo, se solicita reportar para solucionar la situación.

## Programación de sesiones

Visitar la página de [Planificación](/schedule.html).

